"""create demo assessment tables

Revision ID: 0c9577afa9b1
Revises: 
Create Date: 2026-08-21 13:21:20.460999

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0c9577afa9b1'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('demo_assessments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stage', sa.String(length=16), nullable=False),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.Column('demo_label', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stage')
    )
    op.create_table('demo_assessment_questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('assessment_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Text(), nullable=False),
    sa.Column('question_en', sa.Text(), nullable=False),
    sa.Column('option_1_id', sa.Text(), nullable=False),
    sa.Column('option_1_en', sa.Text(), nullable=False),
    sa.Column('option_2_id', sa.Text(), nullable=False),
    sa.Column('option_2_en', sa.Text(), nullable=False),
    sa.Column('option_3_id', sa.Text(), nullable=False),
    sa.Column('option_3_en', sa.Text(), nullable=False),
    sa.Column('option_4_id', sa.Text(), nullable=False),
    sa.Column('option_4_en', sa.Text(), nullable=False),
    sa.Column('correct_option', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['assessment_id'], ['demo_assessments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('assessment_id', 'position', name='uq_demo_question_assessment_position')
    )
    op.create_index(op.f('ix_demo_assessment_questions_assessment_id'), 'demo_assessment_questions', ['assessment_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_demo_assessment_questions_assessment_id'), table_name='demo_assessment_questions')
    op.drop_table('demo_assessment_questions')
    op.drop_table('demo_assessments')
    # ### end Alembic commands ###
